// Mocks generated by Mockito 5.4.5 from annotations
// in exam_app/test/data/api/data_source_impl/login/log_in_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:exam_app/data/api/api_client.dart' as _i7;
import 'package:exam_app/data/api/dto/forget_password/requests/forget_password_request_dto.dart'
    as _i11;
import 'package:exam_app/data/api/dto/forget_password/responses/forget_password_response_dto.dart'
    as _i4;
import 'package:exam_app/data/api/dto/login/requests/login_request_dto.dart'
    as _i10;
import 'package:exam_app/data/api/dto/login/responses/login_response_dto.dart'
    as _i3;
import 'package:exam_app/data/api/dto/reset_password/request/reset_password_request_dto.dart'
    as _i13;
import 'package:exam_app/data/api/dto/reset_password/response/reset_password_response_dto.dart'
    as _i6;
import 'package:exam_app/data/api/dto/sign_up/request/sign_up_request.dart'
    as _i9;
import 'package:exam_app/data/api/dto/sign_up/response/sign_up_response.dart'
    as _i2;
import 'package:exam_app/data/api/dto/verification/request/verify_request_dto.dart'
    as _i12;
import 'package:exam_app/data/api/dto/verification/response/verify_response_dto.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSignUpResponseDto_0 extends _i1.SmartFake
    implements _i2.SignUpResponseDto {
  _FakeSignUpResponseDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoginResponseDto_1 extends _i1.SmartFake
    implements _i3.LoginResponseDto {
  _FakeLoginResponseDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeForgetPasswordResponseDto_2 extends _i1.SmartFake
    implements _i4.ForgetPasswordResponseDto {
  _FakeForgetPasswordResponseDto_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVerifyResponseDto_3 extends _i1.SmartFake
    implements _i5.VerifyResponseDto {
  _FakeVerifyResponseDto_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResetPasswordResponseDto_4 extends _i1.SmartFake
    implements _i6.ResetPasswordResponseDto {
  _FakeResetPasswordResponseDto_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i7.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.SignUpResponseDto> signUp(_i9.SignUpRequestDto? request) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [request]),
            returnValue: _i8.Future<_i2.SignUpResponseDto>.value(
              _FakeSignUpResponseDto_0(
                this,
                Invocation.method(#signUp, [request]),
              ),
            ),
          )
          as _i8.Future<_i2.SignUpResponseDto>);

  @override
  _i8.Future<_i3.LoginResponseDto> login(_i10.LoginRequestDto? request) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue: _i8.Future<_i3.LoginResponseDto>.value(
              _FakeLoginResponseDto_1(
                this,
                Invocation.method(#login, [request]),
              ),
            ),
          )
          as _i8.Future<_i3.LoginResponseDto>);

  @override
  _i8.Future<_i4.ForgetPasswordResponseDto> forgetPassword(
    _i11.ForgetPasswordRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [request]),
            returnValue: _i8.Future<_i4.ForgetPasswordResponseDto>.value(
              _FakeForgetPasswordResponseDto_2(
                this,
                Invocation.method(#forgetPassword, [request]),
              ),
            ),
          )
          as _i8.Future<_i4.ForgetPasswordResponseDto>);

  @override
  _i8.Future<_i5.VerifyResponseDto> verificationCode(
    _i12.VerifyRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verificationCode, [request]),
            returnValue: _i8.Future<_i5.VerifyResponseDto>.value(
              _FakeVerifyResponseDto_3(
                this,
                Invocation.method(#verificationCode, [request]),
              ),
            ),
          )
          as _i8.Future<_i5.VerifyResponseDto>);

  @override
  _i8.Future<_i6.ResetPasswordResponseDto> resetPassword(
    _i13.ResetPasswordRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [request]),
            returnValue: _i8.Future<_i6.ResetPasswordResponseDto>.value(
              _FakeResetPasswordResponseDto_4(
                this,
                Invocation.method(#resetPassword, [request]),
              ),
            ),
          )
          as _i8.Future<_i6.ResetPasswordResponseDto>);
}
